#!/bin/sh

USER="opiopan"
SUSSH=/var/www/wakeserver/sbin/sussh

COMMAND="$1"
IPADDR="$2"
MACADDR="$3"
INTERVAL="$4"
ATTRIBUTE="$5"
VALUE="$6"

checkactive() {
    wakeonlan $2 >/dev/null
    count=0
    while [ $count -lt 10 ];do
	if ping -c1 -w1 $1 >/dev/null ;then
	    if [ $count -gt 0 ];then
		sleep 3
	    fi
	    return 0
	fi
	count=`expr $count + 1`
    done
}

case "$COMMAND" in
    attribute)
	if [ "$ATTRIBUTE" = airplay ];then
	    if [ "$VALUE" = "off" ];then
		CMD=pause
	    else
		CMD=play
	    fi
	    checkactive $IPADDR $MACADDR
	    $SUSSH $USER $IPADDR "jukebox $CMD $VALUE"
	    echo "$VALUE"
	else
	    exit 1
	fi
	;;
    *)
	exit 1
	;;
esac
exit 0
