#!/bin/sh

USER="OPIO"
PASS="0000"
AMPSTATUS="/run/wakeserver/onkyo-amp.status"

COMMAND="$1"
IPADDR="$2"
MACADDR="$3"
INTERVAL="$4"
ATTRIBUTE="$5"
VALUE="$6"

IRTX="irtx 192.168.22.31 nec"

POWER=40BD12
CHANNEL=40BD
PAUSEPLAY=40BD50
SKIPF=40BC26
SKIPB=40BC27
ALTSKIPF=40BC23
ALTSKIPB=40BC22

case "$COMMAND" in
    diag)
	if ping -c1 -W"$INTERVAL" "$IPADDR" >/dev/null;then
	    sleep "$INTERVAL"
	    AMP=`cat $AMPSTATUS`
	    if [ "$AMP" = "off" ] || [ "$AMP" = "on !1SLI00" ];then
		exit 1
	    else
		exit 0
	    fi
	else
	    exit 1
	fi
	;;
    on)
	$IRTX "$POWER" > /dev/null
	;;
    off)
	$IRTX "$POWER" > /dev/null
	;;
    attribute)
	if [ "$ATTRIBUTE" = tvchannel ];then
	    if [ "$VALUE" = "" ];then
		echo 99
		exit 0
	    fi
	    if [ "$VALUE" -lt 1 ] || [ "$VALUE" -gt 12 ];then
		echo 'unsupported channel number was specified'
		exit 1
	    fi
	    NUM=`printf '%.2x' "$VALUE"`
	    $IRTX "$CHANNEL""$NUM" > /dev/null
	    echo "$VALUE"
	elif [ "$ATTRIBUTE" = tvband ];then
	    if [ "$VALUE" = "" ]; then
		echo unknown
		exit 0
	    fi
	    case "$VALUE" in
		terrestrial)
		    CMD=40BD7A
		    ;;
		bs)
		    CMD=40BD7C
		    ;;
		cs)
		    CMD=40BD7D
		    ;;
		*)
		    exit 1
		    ;;
	    esac
	    $IRTX "$CMD" > /dev/null
	    echo "$VALUE"
	elif [ "$ATTRIBUTE" = tvchannelname ];then
	    if [ "$VALUE" = "" ];then
		echo unknown
		exit 0
	    fi
	    echo "$VALUE" | tr '-' '\n' | while read ITEM;do
		PRECMD=""
		PRECMD2=""
		CMD=""
		case "$ITEM" in
		    TV)
			SUFFIX=40BD7A
			;;
		    BS)
			PRECMD=40BD7A
			SUFFIX=40BD7C
			;;
		    BS2)
			PRECMD=40BD7A
			PRECMD2=40BD7C
			SUFFIX=40BD7C
			;;
		    CS)
			SUFFIX=40BD7D
			;;
		    *)
			if [ "$ITEM" -ge 1 ] || [ "$ITEM" -le 12 ];then
			    :
			else
			    echo 'unsupported channel number was specified'
			    exit 1
			fi
			CMD="$CHANNEL"
			SUFFIX=`printf '%.2x' "$ITEM"`
			;;
		esac
		if ! [ "$PRECMD" = "" ]; then
		    $IRTX "$PRECMD" > /dev/null
		    sleep 0.1
		    if ! [ "$PRECMD2" = "" ]; then
			sleep 0.2
			$IRTX "$PRECMD2" > /dev/null
			sleep 0.3
		    fi
		fi
		$IRTX "$CMD""$SUFFIX" > /dev/null
	    done || exit 1
	    echo "$VALUE"
	elif [ "$ATTRIBUTE" = player ];then
	    if [ "$VALUE" = "" ]; then
		echo unknown
		exit 0
	    fi
	    case "$VALUE" in
		pauseplay)
		    CMD=$PAUSEPLAY
		    ;;
		skipf)
		    CMD=$SKIPF
		    ;;
		skipb)
		    CMD=$SKIPB
		    ;;
		altskipf)
		    CMD=$ALTSKIPF
		    ;;
		altskipb)
		    CMD=$ALTSKIPB
		    ;;
		*)
		    exit 1
		    ;;
	    esac
	    $IRTX "$CMD" > /dev/null
	    echo unknown
	elif [ "$ATTRIBUTE" = volumerelative ];then
	    if [ "$VALUE" = "" ]; then
		echo unknown
		exit 0
	    fi
	    case "$VALUE" in
		increase)
		    CMD=40BF1A
		    ;;
		decrease)
		    CMD=40BF1E
		    ;;
		*)
		    exit 1
		    ;;
	    esac
	    $IRTX "$CMD" > /dev/null
	    echo unknown
	else
	    exit 1
	fi
	;;
    *)
	exit 1
	;;
esac
