#!/bin/sh

USER="OPIO"
PASS="0000"
AMPSTATUS="/run/wakeserver/onkyo-amp.status"

COMMAND="$1"
IPADDR="$2"
MACADDR="$3"
INTERVAL="$4"
ATTRIBUTE="$5"
VALUE="$6"

IRTX="irtx elflet-living.local nec"

POWER=40BD12ED
CHANNEL=40BD
PAUSEPLAY=40BD50AF
SKIPF=40BC26D9
SKIPB=40BC27D8
ALTSKIPF=40BC23DC
ALTSKIPB=40BC22DD

case "$COMMAND" in
    diag)
	if ping -c1 -W"$INTERVAL" "$IPADDR" >/dev/null;then
	    sleep "$INTERVAL"
	    AMP=`cat $AMPSTATUS`
	    if [ "$AMP" = "off" ] || [ "$AMP" = "on !1SLI00" ];then
		exit 1
	    else
		exit 0
	    fi
	else
	    exit 1
	fi
	;;
    on)
	$IRTX "$POWER" > /dev/null
	;;
    off)
	$IRTX "$POWER" > /dev/null
	;;
    attribute)
	if [ "$ATTRIBUTE" = tvchannel ];then
	    if [ "$VALUE" = "" ];then
		echo 99
		exit 0
	    fi
	    if [ "$VALUE" -lt 1 ] || [ "$VALUE" -gt 12 ];then
		echo 'unsupported channel number was specified'
		exit 1
	    fi
	    NUM=`printf '%.2x%.2x' "$VALUE" $((~"$VALUE" & 0xff))`
	    $IRTX "$CHANNEL""$NUM" > /dev/null
	    echo "$VALUE"
	elif [ "$ATTRIBUTE" = tvband ];then
	    if [ "$VALUE" = "" ]; then
		echo unknown
		exit 0
	    fi
	    case "$VALUE" in
		terrestrial)
		    CMD=40BD7A85
		    ;;
		bs)
		    CMD=40BD7C83
		    ;;
		cs)
		    CMD=40BD7D82
		    ;;
		*)
		    exit 1
		    ;;
	    esac
	    $IRTX "$CMD" > /dev/null
	    echo "$VALUE"
	elif [ "$ATTRIBUTE" = tvchannelname ];then
	    if [ "$VALUE" = "" ];then
		echo unknown
		exit 0
	    fi
	    echo "$VALUE" | tr '-' '\n' | while read ITEM;do
		PRECMD=""
		PRECMD2=""
		CMD=""
		case "$ITEM" in
		    TV)
			SUFFIX=40BD7A85
			;;
		    BS)
			PRECMD=40BD7A85
			SUFFIX=40BD7C83
			;;
		    BS2)
			PRECMD=40BD7A85
			PRECMD2=40BD7C83
			SUFFIX=40BD7C83
			;;
		    CS)
			SUFFIX=40BD7D82
			;;
		    *)
			if [ "$ITEM" -ge 1 ] || [ "$ITEM" -le 12 ];then
			    :
			else
			    echo 'unsupported channel number was specified'
			    exit 1
			fi
			CMD="$CHANNEL"
			SUFFIX=`printf '%.2x%.2x' "$ITEM" $((~$ITEM & 0xff))`
			;;
		esac
		if ! [ "$PRECMD" = "" ]; then
		    $IRTX "$PRECMD" > /dev/null
		    sleep 0.1
		    if ! [ "$PRECMD2" = "" ]; then
			sleep 0.1
			$IRTX "$PRECMD2" > /dev/null
			sleep 0.2
		    fi
		fi
		$IRTX "$CMD""$SUFFIX" > /dev/null
		sleep 0.1
	    done || exit 1
	    echo "$VALUE"
	elif [ "$ATTRIBUTE" = player ];then
	    if [ "$VALUE" = "" ]; then
		echo unknown
		exit 0
	    fi
	    case "$VALUE" in
		pauseplay)
		    CMD=$PAUSEPLAY
		    ;;
		skipf)
		    CMD=$SKIPF
		    ;;
		skipb)
		    CMD=$SKIPB
		    ;;
		altskipf)
		    CMD=$ALTSKIPF
		    ;;
		altskipb)
		    CMD=$ALTSKIPB
		    ;;
		*)
		    exit 1
		    ;;
	    esac
	    $IRTX "$CMD" > /dev/null
	    echo unknown
	elif [ "$ATTRIBUTE" = volumerelative ];then
	    if [ "$VALUE" = "" ]; then
		echo unknown
		exit 0
	    fi
	    case "$VALUE" in
		increase)
		    CMD=40BF1AE5
		    ;;
		decrease)
		    CMD=40BF1EE1
		    ;;
		*)
		    exit 1
		    ;;
	    esac
	    $IRTX "$CMD" > /dev/null
	    echo unknown
	else
	    exit 1
	fi
	;;
    *)
	exit 1
	;;
esac
