#!/bin/sh

SLEEP_DEFFERED=120
STOP_TIME=/run/wakeserver/musicstopping.time

URL='http://localhost:8080/servers'
TVNAME=TV%20@living%20%231
AMPNAME=AV%20amplifier
STOPCMD='{"isOn":false}'
AMPSTARTCMD='{"isOn":true,"attributes":{"selector":0,"volume":26}}'

ison(){
    SERVER="$1"
    curl -s "$URL/$SERVER" | python -m json.tool |
	awk '
            BEGIN {rc = 1}
	    $1 == "\"isOn\":"{
                if ($2 == "true"){
                    rc = 0;
                    exit;
                }else{
                    rc = 1;
                    exit;
                }
            }
            END {exit rc}
        '
}

post(){
    SERVER="$1"
    DATA="$2"
    curl -s -XPOST -H'Content-Type: application/json' -d"$DATA" "$URL/$SERVER"
}

CMD="$1"

case "$CMD" in
    start)
	rm -f $STOP_TIME
	if ison "$TVNAME";then
	    post "$TVNAME" "$STOPCMD"
	    while ison "$AMPNAME" ;do
		echo 'tv checking'
		sleep 0.5
	    done
	    sleep 2
	    post "$AMPNAME" "$AMPSTARTCMD"
	else
	    post "$AMPNAME" "$AMPSTARTCMD"
	fi
	;;
    stop)
	date +%s > $STOP_TIME
	(
	    sleep $SLEEP_DEFFERED
	    threshold=`expr $SLEEP_DEFFERED - 5`
	    now=`date +%s`
	    past=`cat $STOP_TIME`
	    if [ "$past" != ""  ] && \
	       [ `expr $now - $past` -gt $threshold ];then
		if ! ison "$TVNAME";then
		    post "$AMPNAME" "$STOPCMD"
		fi
	    fi 
	)&
	;;
esac
