#!/bin/sh

IPADDR="$1"
MACADDR="$2"
INTERVAL="$3"

if ping -c1 -W"$INTERVAL" "$IPADDR" >/dev/null;then
    sleep "$INTERVAL"
    if wget --quiet -O - "http://$IPADDR/index.html" | \
	grep 'Operate after turning the power on' >/dev/null;then
	exit 1
    else
	exit 0
    fi
else
    exit 1
fi