#!/bin/sh

COMMAND="$1"
IPADDR="$2"
MACADDR="$3"
INTERVAL="$4"

case "$COMMAND" in
    diag)
	if ping -c1 -W"$INTERVAL" "$IPADDR" >/dev/null;then
	    sleep "$INTERVAL"
	    if wget --quiet -O - "http://$IPADDR/index.html" | \
		grep 'Operate after turning the power on' >/dev/null;then
		exit 1
	    else
		exit 0
	    fi
	else
	    exit 1
	fi
	;;
    on | off | *)
	exit 1
	;;
esac
