#!/usr/bin/python

import os
import sys
import signal
import time
import json
from collections import namedtuple
from wakeserver import monitoring, plugin, webservice, cecmonitor

SEP = '-----------------------------------------------------------------------'

PIDFILE =          "/run/wakeserverd.pid"
STATUS_DIR =       "/run/wakeserver"
ERROR_FILE =       "/run/wakeserver/error"

MAIN_CONF =        "/var/www/wakeserver/wakeserver.conf"
SERVERS_CONF =     "/var/www/wakeserver/servers.conf"
WEB_ROOT =          "/var/www/wakeserver/html"
PLUGIN_DIR =       "/var/www/wakeserver/plugin.py"
OLD_PLUGIN_DIR =    "/var/www/wakeserver/plugin"

def daemonize(inDebug):
    if not inDebug:
        os.chdir("/")

    if not os.path.isdir(STATUS_DIR):
        os.mkdir(STATUS_DIR)
        os.chmod(STATUS_DIR, 0777)
    if not inDebug:
        sys.stdin.close()
        sys.stdout.close()
        sys.stderr.close()
        sys.stdin = open("/dev/null", "r")
        sys.stdout = open("/dev/null", "w")
        sys.stderr = open(ERROR_FILE, "w")

    return True

def main():
    global MAIN_CONF
    global SERVERS_CONF
    global WEB_ROOT
    global PLUGIN_DIR
    global OLD_PLUG_DIR
    if 'SERVERS_CONF' in os.environ:
        SERVERS_CONF = os.environ['SERVERS_CONF']
    if 'WAKESERVER_CONF' in os.environ:
        MAIN_CONF = os.environ['WAKESERVER_CONF']
    if 'WEB_ROOT' in os.environ:
        WEB_ROOT = os.environ['WEB_ROOT']
    if 'PLUGIN_DIR' in os.environ:
        PLUGIN_DIR = os.environ['PLUGIN_DIR']
    
    if daemonize('DEBUG' in os.environ):
        conf = namedtuple('Config', ('main', 'servers'))
        with open(MAIN_CONF) as f:
            conf.main = json.load(f)
            
        with open(SERVERS_CONF) as f:
            conf.servers = json.load(f)

        serverType = conf.main['server_type'] \
               if 'server_type' in conf.main else 'master'
        isMaster = serverType == 'master'
        
        print SEP
        print 'WakeServer daemon:'
        print '    WAKESERVER_CONF: ' + MAIN_CONF
        print '    SERVERS_CONF:    ' + SERVERS_CONF
        print '    WEB_ROOT:        ' + WEB_ROOT
        print '    PLUGIN_DIR:      ' + PLUGIN_DIR
        print '    OLD_PLUGIN_DIR:  ' + OLD_PLUGIN_DIR
        print ''
        print '    Daemon Type:     ' + serverType
        print SEP
            
        pool = plugin.PluginPool(conf, 
                                 pluginDir = PLUGIN_DIR)
        monitor = monitoring.Monitor(conf, pool)
        monitoring.monitor = monitor
        monitor.start()

        cecmonitor.startCECmonitor(conf, monitor)

        webservice.serveForever(monitor, pool, isMaster, WEB_ROOT)

if __name__ == '__main__':
    def sigintHandler(signal, frame):
        quit()
    signal.signal(signal.SIGINT, sigintHandler)
    main()
    sys.exit(0)
