#!/usr/bin/python3

import sys
import json

def printUsage():
    print('usage: extjson <FILE> <ELEMENT-NAME>', file=sys.stderr)

def main():
    args = sys.argv
    if len(args) != 3:
        printUsage()
        return 1

    file=args[1]
    key=args[2]

    with open(file) as f:
        object = json.load(f)
        if key in object :
            print(object[key])

    return 0

if __name__ == '__main__':
    sys.exit(main())
